# Generated by Django 2.0.3 on 2018-04-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180328_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.TextField(default=''),
        ),
    ]
